services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    depends_on:
      - pocketbase
    ports:
      - "8080:8080"
    volumes:
      - ./proxy/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./client/dist:/usr/share/nginx/html
    extra_hosts:
      - geoffjay.local:127.0.0.1
      - api.geoffjay.local:127.0.0.1
      - app.geoffjay.local:127.0.0.1

  pocketbase:
    container_name: pocketbase
    build:
      context: ./pocketbase
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./pocketbase/data:/pb/pb_data

  api:
    container_name: api
    build:
      context: ./api
    restart: unless-stopped
    ports:
      - "8082:8080"
    volumes:
      - ./api:/api

  app:
    container_name: app
    build:
      context: ./app
      dockerfile: dev.Dockerfile
    restart: unless-stopped
    ports:
      - "8083:5173"
    volumes:
      - ./app:/app
