version: "3"

tasks:
  dev:
    desc: "Run development environment"
    cmds:
      - overmind start
  api/build:
    dir: ./api
    cmds:
      - go build -o ./bin/api
  api/watch:
    dir: ./api
    cmds:
      - air
  client/style/build:
    dir: ./client
    cmds:
      - npx tailwindcss -i ./main.css -o ./tailwind.css
  client/style/watch:
    dir: ./client
    cmds:
      - npx tailwindcss -i ./main.css -o ./tailwind.css --watch
