version: "3"

tasks:
  dev:
    desc: "Run development environment"
    cmds:
      - overmind start
  api/build:
    dir: ./api
    cmds:
      - go build -o ./bin/api
  api/dev:
    dir: ./api
    cmds:
      - air
  client/dev:
    dir: ./client
    cmds:
      - yarn dev
