version: "3"

tasks:
  core:
    desc: "Run docker compose core profile"
    cmds:
      - docker compose --profile core up
  dev:
    desc: "Run development environment"
    cmds:
      - task: core
      - overmind start
  api/build:
    dir: ./api
    cmds:
      - go build -o ./bin/api
  api/dev:
    dir: ./api/health
    cmds:
      - air
  client/dev:
    dir: ./client
    cmds:
      - yarn dev
  photo/dev:
    dir: ./photo
    cmds:
      - yarn dev
