#!/bin/bash
set -e

echo "=== WireGuard Client Setup for CoreOS ==="
echo ""
echo "This script sets up WireGuard in a container using Podman quadlets."
echo ""

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root (sudo)"
    exit 1
fi

# Prompt for required values
echo "Enter the following values (generated by generate-keys.sh):"
echo ""

read -p "Client private key: " CLIENT_PRIVATE_KEY
read -p "Gateway public key: " GATEWAY_PUBLIC_KEY
read -p "Fly.io VPN hostname [vpn-geoffjay-com.fly.dev]: " FLY_HOSTNAME
FLY_HOSTNAME=${FLY_HOSTNAME:-vpn-geoffjay-com.fly.dev}

# Detect primary network interface
PRIMARY_IFACE=$(ip route | grep default | awk '{print $5}' | head -1)
echo ""
echo "Detected primary network interface: $PRIMARY_IFACE"
read -p "Use this interface? [Y/n]: " USE_IFACE
if [[ "$USE_IFACE" =~ ^[Nn] ]]; then
    read -p "Enter interface name: " PRIMARY_IFACE
fi

# Create config directory
mkdir -p /etc/wireguard
mkdir -p /etc/containers/systemd

# Create environment file
echo "Creating environment file..."
cat > /etc/wireguard/wireguard.env << EOF
WG_PRIVATE_KEY=${CLIENT_PRIVATE_KEY}
WG_GATEWAY_PUBLIC_KEY=${GATEWAY_PUBLIC_KEY}
WG_ENDPOINT=${FLY_HOSTNAME}:51820
WG_CLIENT_IP=10.10.0.2
WG_ALLOWED_IPS=10.10.0.0/24
HOST_INTERFACE=${PRIMARY_IFACE}
EOF

chmod 600 /etc/wireguard/wireguard.env

# Create WireGuard config for the container
echo "Creating WireGuard configuration..."
cat > /etc/wireguard/wg0.conf << EOF
[Interface]
Address = 10.10.0.2/24
PrivateKey = ${CLIENT_PRIVATE_KEY}

[Peer]
PublicKey = ${GATEWAY_PUBLIC_KEY}
Endpoint = ${FLY_HOSTNAME}:51820
AllowedIPs = 10.10.0.0/24
PersistentKeepalive = 25
EOF

chmod 600 /etc/wireguard/wg0.conf

# Create Podman quadlet file (modern CoreOS way)
echo "Creating Podman quadlet..."
cat > /etc/containers/systemd/wireguard.container << 'EOF'
[Unit]
Description=WireGuard VPN Client
After=network-online.target
Wants=network-online.target

[Container]
Image=docker.io/linuxserver/wireguard:latest
ContainerName=wireguard-client

# Required capabilities for WireGuard
AddCapability=NET_ADMIN
AddCapability=SYS_MODULE

# Sysctls for IP forwarding
Sysctl=net.ipv4.ip_forward=1
Sysctl=net.ipv4.conf.all.src_valid_mark=1

# Host networking required for VPN
Network=host

# Mount WireGuard config and kernel modules
Volume=/etc/wireguard:/config:Z
Volume=/lib/modules:/lib/modules:ro

# Environment
Environment=PUID=0
Environment=PGID=0
Environment=TZ=UTC

[Service]
Restart=always
TimeoutStartSec=300

[Install]
WantedBy=multi-user.target
EOF

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Reload systemd and start the service:"
echo "  sudo systemctl daemon-reload"
echo "  sudo systemctl start wireguard"
echo ""
echo "Enable on boot:"
echo "  sudo systemctl enable wireguard"
echo ""
echo "Check status:"
echo "  sudo systemctl status wireguard"
echo "  sudo podman exec wireguard-client wg show"
echo ""
echo "View logs:"
echo "  sudo podman logs -f wireguard-client"
