#!/bin/bash
set -e

echo "=== WireGuard Client Setup for Fly.io VPN ==="
echo ""

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root (sudo)"
    exit 1
fi

# Detect CoreOS/Fedora CoreOS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    if [[ "$ID" == "coreos" ]] || [[ "$ID" == "fedora" && "$VARIANT_ID" == "coreos" ]]; then
        echo "Detected CoreOS - use setup-coreos.sh instead for container-based setup."
        echo ""
        echo "Run: sudo bash setup-coreos.sh"
        exit 0
    fi
fi

# Standard Linux setup
if ! command -v wg &> /dev/null; then
    echo "Installing WireGuard..."
    if command -v apt-get &> /dev/null; then
        apt-get update && apt-get install -y wireguard wireguard-tools
    elif command -v dnf &> /dev/null; then
        dnf install -y wireguard-tools
    elif command -v yum &> /dev/null; then
        yum install -y wireguard-tools
    elif command -v pacman &> /dev/null; then
        pacman -S --noconfirm wireguard-tools
    else
        echo "ERROR: Cannot detect package manager. Please install WireGuard manually."
        exit 1
    fi
fi

echo ""
echo "Enter the following values (generated by generate-keys.sh):"
echo ""

read -p "Client private key: " CLIENT_PRIVATE_KEY
read -p "Gateway public key: " GATEWAY_PUBLIC_KEY
read -p "Fly.io VPN hostname [vpn-geoffjay-com.fly.dev]: " FLY_HOSTNAME
FLY_HOSTNAME=${FLY_HOSTNAME:-vpn-geoffjay-com.fly.dev}

# Detect primary network interface
PRIMARY_IFACE=$(ip route | grep default | awk '{print $5}' | head -1)
echo ""
echo "Detected primary network interface: $PRIMARY_IFACE"
read -p "Use this interface? [Y/n]: " USE_IFACE
if [[ "$USE_IFACE" =~ ^[Nn] ]]; then
    read -p "Enter interface name: " PRIMARY_IFACE
fi

echo ""
echo "Creating WireGuard configuration..."

cat > /etc/wireguard/wg0.conf << EOF
[Interface]
Address = 10.10.0.2/24
PrivateKey = ${CLIENT_PRIVATE_KEY}

PostUp = sysctl -w net.ipv4.ip_forward=1
PostUp = iptables -A FORWARD -i %i -j ACCEPT
PostUp = iptables -A FORWARD -o %i -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o ${PRIMARY_IFACE} -j MASQUERADE

PostDown = iptables -D FORWARD -i %i -j ACCEPT
PostDown = iptables -D FORWARD -o %i -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o ${PRIMARY_IFACE} -j MASQUERADE

[Peer]
PublicKey = ${GATEWAY_PUBLIC_KEY}
Endpoint = ${FLY_HOSTNAME}:51820
AllowedIPs = 10.10.0.0/24
PersistentKeepalive = 25
EOF

chmod 600 /etc/wireguard/wg0.conf

echo ""
echo "=== Configuration Created ==="
echo ""
echo "To start the VPN connection:"
echo "  sudo wg-quick up wg0"
echo ""
echo "To enable on boot:"
echo "  sudo systemctl enable wg-quick@wg0"
echo ""
echo "To check status:"
echo "  sudo wg show"
echo ""
echo "To stop the VPN:"
echo "  sudo wg-quick down wg0"
