import { Project, ProjectStatus } from "./types";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "p1",
    name: "geoffjay.com",
    description:
      "Personal portfolio website built with Vite, HTMX, and Tailwind CSS. Features a minimalist design with dark mode support and smooth animations.",
    imageUrl: "https://picsum.photos/id/1/800/600",
    githubUrl: "https://github.com/geoffjay/geoffjay.com",
    liveUrl: "https://geoffjay.com",
    technologies: ["Vite", "HTMX", "Tailwind", "TypeScript"],
    status: ProjectStatus.COMPLETED,
    progress: 100,
    startDate: "2024-01-15T00:00:00Z",
    lastUpdated: "2024-12-20T00:00:00Z",
    featured: true,
  },
  {
    id: "p2",
    name: "Task Manager CLI",
    description:
      "A command-line task management tool written in Rust. Supports projects, tags, priorities, and due dates with SQLite storage.",
    imageUrl: "https://picsum.photos/id/2/800/600",
    githubUrl: "https://github.com/geoffjay/task-cli",
    technologies: ["Rust", "SQLite", "Clap"],
    status: ProjectStatus.IN_PROGRESS,
    progress: 65,
    startDate: "2024-06-01T00:00:00Z",
    lastUpdated: "2024-12-18T00:00:00Z",
    featured: true,
  },
  {
    id: "p3",
    name: "Home Automation Hub",
    description:
      "Centralized home automation system using Go microservices. Integrates with Zigbee, Z-Wave, and MQTT devices.",
    imageUrl: "https://picsum.photos/id/3/800/600",
    githubUrl: "https://github.com/geoffjay/home-hub",
    technologies: ["Go", "MQTT", "Docker", "PostgreSQL"],
    status: ProjectStatus.IN_PROGRESS,
    progress: 40,
    startDate: "2024-03-10T00:00:00Z",
    lastUpdated: "2024-12-15T00:00:00Z",
    featured: false,
  },
  {
    id: "p4",
    name: "Photo Organizer",
    description:
      "AI-powered photo organization tool using Google Gemini for automatic tagging and categorization.",
    imageUrl: "https://picsum.photos/id/4/800/600",
    githubUrl: "https://github.com/geoffjay/photo-organizer",
    liveUrl: "https://photos.geoffjay.com",
    technologies: ["React", "TypeScript", "Gemini AI", "Vite"],
    status: ProjectStatus.COMPLETED,
    progress: 100,
    startDate: "2024-08-20T00:00:00Z",
    lastUpdated: "2024-11-30T00:00:00Z",
    featured: true,
  },
  {
    id: "p5",
    name: "API Gateway",
    description:
      "Lightweight API gateway with rate limiting, authentication, and request transformation capabilities.",
    imageUrl: "https://picsum.photos/id/5/800/600",
    githubUrl: "https://github.com/geoffjay/api-gateway",
    technologies: ["Go", "Redis", "gRPC", "Protobuf"],
    status: ProjectStatus.PLANNING,
    progress: 10,
    startDate: "2024-11-01T00:00:00Z",
    lastUpdated: "2024-12-01T00:00:00Z",
    featured: false,
  },
  {
    id: "p6",
    name: "Music Visualizer",
    description:
      "Real-time audio visualization using WebGL and the Web Audio API. Features multiple visualization modes and Spotify integration.",
    imageUrl: "https://picsum.photos/id/6/800/600",
    githubUrl: "https://github.com/geoffjay/music-viz",
    liveUrl: "https://viz.geoffjay.com",
    technologies: ["WebGL", "TypeScript", "Web Audio API"],
    status: ProjectStatus.ON_HOLD,
    progress: 75,
    startDate: "2023-09-15T00:00:00Z",
    lastUpdated: "2024-02-10T00:00:00Z",
    featured: false,
  },
  {
    id: "p7",
    name: "Budget Tracker",
    description:
      "Personal finance tracking application with bank sync, budgeting, and spending analytics.",
    imageUrl: "https://picsum.photos/id/7/800/600",
    githubUrl: "https://github.com/geoffjay/budget-tracker",
    technologies: ["React", "Node.js", "PostgreSQL", "Plaid"],
    status: ProjectStatus.ARCHIVED,
    progress: 90,
    startDate: "2022-05-01T00:00:00Z",
    lastUpdated: "2023-08-15T00:00:00Z",
    featured: false,
  },
  {
    id: "p8",
    name: "Code Snippet Manager",
    description:
      "Desktop application for organizing and searching code snippets with syntax highlighting and cloud sync.",
    imageUrl: "https://picsum.photos/id/8/800/600",
    githubUrl: "https://github.com/geoffjay/snippets",
    technologies: ["Rust", "GPUI", "SQLite"],
    status: ProjectStatus.IN_PROGRESS,
    progress: 30,
    startDate: "2024-10-01T00:00:00Z",
    lastUpdated: "2024-12-19T00:00:00Z",
    featured: true,
  },
  {
    id: "p9",
    name: "Weather Dashboard",
    description:
      "Beautiful weather dashboard with forecasts, radar maps, and severe weather alerts.",
    imageUrl: "https://picsum.photos/id/9/800/600",
    githubUrl: "https://github.com/geoffjay/weather",
    liveUrl: "https://weather.geoffjay.com",
    technologies: ["Svelte", "TypeScript", "OpenWeatherMap"],
    status: ProjectStatus.COMPLETED,
    progress: 100,
    startDate: "2024-04-01T00:00:00Z",
    lastUpdated: "2024-07-20T00:00:00Z",
    featured: false,
  },
  {
    id: "p10",
    name: "Documentation Generator",
    description:
      "Automated documentation generator that analyzes codebases and produces comprehensive technical docs.",
    imageUrl: "https://picsum.photos/id/10/800/600",
    githubUrl: "https://github.com/geoffjay/docgen",
    technologies: ["Python", "OpenAI", "Markdown"],
    status: ProjectStatus.PLANNING,
    progress: 5,
    startDate: "2024-12-01T00:00:00Z",
    lastUpdated: "2024-12-10T00:00:00Z",
    featured: false,
  },
];

export const STATUS_LABELS: Record<ProjectStatus, string> = {
  [ProjectStatus.PLANNING]: "Planning",
  [ProjectStatus.IN_PROGRESS]: "In Progress",
  [ProjectStatus.COMPLETED]: "Completed",
  [ProjectStatus.ON_HOLD]: "On Hold",
  [ProjectStatus.ARCHIVED]: "Archived",
};

export const STATUS_COLORS: Record<ProjectStatus, string> = {
  [ProjectStatus.PLANNING]: "bg-purple-100 text-purple-700",
  [ProjectStatus.IN_PROGRESS]: "bg-blue-100 text-blue-700",
  [ProjectStatus.COMPLETED]: "bg-green-100 text-green-700",
  [ProjectStatus.ON_HOLD]: "bg-yellow-100 text-yellow-700",
  [ProjectStatus.ARCHIVED]: "bg-gray-100 text-gray-600",
};
