name: Test NGINX Config

on: [push, pull_request]

jobs:
  test-nginx-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NGINX
        run: sudo apt-get update && sudo apt-get install -y nginx

      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 geoffjay.com" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 app.geoffjay.com" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 blog.geoffjay.com" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 app-geoffjay-com.internal" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 blog-geoffjay-com.internal" | sudo tee -a /etc/hosts

      - name: Test NGINX config
        run: sudo nginx -t -c ${{ github.workspace }}/proxy/nginx.conf
